### ISSUE TITLE
Plans to add PWA config templates?

### ISSUE THREAD

**Issue by brendanmatkin** [preactjs/create-preact#15]
I'm wondering if there are plans to add the PWA configuration features of preact-cli. If so, what is the expected timeline? Thanks!

**Comment by brendanmatkin** [comment]
Ok cool! I'm just tinkering with rebuilding an old react PWA, and seems like Preact is a really nice way to do that. And I really love using Vite and I really hate using webpack haha! 

I was looking at vite-plugin-pwa and it seems pretty slick! I think I'll give it a go. 

Thanks for the quick reply.

**Comment by rschristian** [comment]
Going to close this out as I don't think we'll be adding this any time soon.

Alongside options like Typescript, routing, prerendering, etc., PWAs are unlikely to hit the same level of importance or use. `vite-plugin-pwa` has Preact docs & examples as-is, which should cover users pretty well.

Thanks though!
