### ISSUE TITLE
Add router as valid SSG option

### ISSUE THREAD

**Issue by rschristian** [preactjs/create-preact#5]
Right now we only support adding a router to [pure client-side apps](https://github.com/preactjs/create-preact/blob/a99b4f70eae82fb262986f289bee35a0b1bc27b4/src/index.js#L56-L60) but we should expand this to SSG as well. Just need to add a `config/router-ssg` directory I think, mirroring what we've done w/ `base` and `config/router` more or less.

**Comment by JoviDeCroock** [comment]
The current SSG implementation already uses a router internally, it has the FS-based routing. We could leverage [route functions](https://vite-plugin-ssr.com/routing#route-strings-route-functions) to extend this but not sure about the effort involved here.

**Comment by rschristian** [comment]
Ah, fair enough! I (obviously) only skimmed the impl, will need to look at that more.

In that case, it's probably worth adding a second page just so that's immediately obvious. I'll probably do that later once I've actually had a peek at the docs.

**Comment by rschristian** [comment]
Do we want to promote server-side routing over of client-side? That was more of what I was getting at, though I was only vaguely aware of what the SSG implementation was doing.

**Comment by JoviDeCroock** [comment]
To me it's about providing the option rather than promoting it. In Preact-cli we had an easy way to support all so I figured we might need an ssg/prerender getting started here as well

**Comment by rschristian** [comment]
I totally agree, but to be clear, the SSG template right now is server-side routing. It's catching a few people off guard that I'm trying to help migrate over from preact-cli specifically.

The question is more what we're after, pure SSG without client-side routing, or do we want prerendering à la Preact-CLI, WMR, etc.?

**Comment by rschristian** [comment]
Going to close this out, I want to have a rethink of SSR/prerendering in general.
