### ISSUE TITLE
vite-plugin-ssr name has change to Vike

### ISSUE THREAD

**Issue by Hillsie** [preactjs/create-preact#9]
In future, the `package.json` and references to `vite-plugin-ssr` would need to change over to `vike`

https://vike.dev/

https://vite-plugin-ssr.com/vike

Happy to raise a PR if it helps out.

**Comment by rschristian** [comment]
I'm currently in the process of replacing it completely so it's probably fine as-is for now, but thanks for the heads up!

**Comment by Hillsie** [comment]
Just saw it was closed ....  All good. 🙂️ Thought you might be out of my time zone 💤️, so did some updating and manual testing on a branch ...  no worries ... please close of the PR
